site_name: My Docs

theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: indigo
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-night
        name: ダークモードに切り替え
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.8/clipboard.min.js

use_directory_urls: false

site_url: https://kasagi-e-grid.github.io/kasagi_MkDocs/

nav:
    - はじめに: index.md
    - サーバ構成について: server/architecture.md
    - Apacheについて: server/server.md
    - NFSについて: server/nfs.md
    - Git運用について: git/operation.md
    - デプロイについて: deploy/flow.md
    - Mkdocsについて: mkdocs/index.md
